package com.nudgefit.model.enums;

public enum ConversationState {
    NEW_USER,
    ONBOARDING_NAME,
    ONBOARDING_CURRENT_WEIGHT,
    ONBOARDING_HEIGHT,
    ONBOARDING_AGE,
    ONBOARDING_GENDER,
    ONBOARDING_ACTIVITY_LEVEL,
    ONBOARDING_FAT_GOAL,
    ONBOARDING_CURRENT_BODY_FAT,
    ONBOARDING_TARGET_BODY_FAT,
    ONBOARDING_MUSCLE_GOAL,
    ONBOARDING_CURRENT_MUSCLE_MASS,
    ONBOARDING_TARGET_MUSCLE_MASS,
    ONBOARDING_INTENSITY_LEVEL,
    ACTIVE
}
